### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by play113** [GRVYDEV/Project-Lightspeed#25]
I unfortunately have too little experience with rust, can someone help me further

THX

Build on Ubuntu 20.04.1 LTS
rustc 1.43.0

#> cargo build 
...
...
   Compiling tokio-stream v0.1.1
   Compiling tokio-util v0.6.0
error[E0277]: the trait bound `std::io::IoSlice<'_>: std::marker::Copy` is not satisfied
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-util-0.6.0/src/lib.rs:189:30
    |
189 |             let mut slices = [IoSlice::new(&[]); MAX_BUFS];
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::marker::Copy` is not implemented for `std::io::IoSlice<'_>`
    |
    = note: the `Copy` trait is required because the repeated element will be copied

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `tokio-util`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by GRVYDEV** [comment]
This is an error caused by an outdated version of rustc! Tokio-util version 0.6.0 has been confirmed to compile on rustc version 1.48.0 and later! There seems to be an issue with the ubuntu rustc package (its outdated) so I would advise following [these](https://www.rust-lang.org/tools/install) instructions for installing rustc and it should fix your problem!

**Comment by play113** [comment]
thx for the fast response ... i am testing this immediately

**Comment by GRVYDEV** [comment]
Let me know how it goes!

**Comment by play113** [comment]
works fine with rustc 1.49.0 (e1884a8e3 2020-12-29)
thx for the super fast response and the appropriate hint

**Comment by GRVYDEV** [comment]
No worries I am here to help! Glad you got it working!

**Comment by play113** [comment]
i still need to put it together and marry it to OBS but i am in good spirits ;)

**Comment by GRVYDEV** [comment]
> i still need to put it together and marry it to OBS but i am in good spirits ;)

Let me know if you run into any other issues! Also feel free to join the discord since its a bit easier to help on there!
